TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL;
TRUNCATE TABLE DOC_AI_DB.DOC_AI_SCHEMA.STAGED_FILES;

REMOVE @DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_STAGE/*;