USE DATABASE DOC_AI_DB;

CREATE OR REPLACE TABLE DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS
(
    ID VARCHAR(16777216) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    ORGANIZATION_NAME VARCHAR(16777216),
    APP_USER_ID_CREATED_BY VARCHAR(16777216),
    APP_USER_ID_MODIFIED_BY VARCHAR(16777216),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(16777216),
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(16777216)
)
;

CREATE OR REPLACE TABLE DOC_AI_DB.SECURITY_SCHEMA.USERS
(
    ID VARCHAR(16777216) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    ORGANIZATION_ID VARCHAR(16777216),
    USER_NAME VARCHAR(16777216),
    PASSWORD VARCHAR(16777216),
    FIRST_NAME VARCHAR(16777216),
    LAST_NAME VARCHAR(16777216),
    EMAIL_ADDRESS VARCHAR(16777216),
    APP_USER_ID_CREATED_BY INT,
    APP_USER_ID_MODIFIED_BY INT,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(16777216),
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(16777216)
)
;


INSERT INTO DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS(ORGANIZATION_NAME, CREATED_BY, MODIFIED_BY) VALUES('Alpha Corporation', CURRENT_USER(), CURRENT_USER());
INSERT INTO DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS(ORGANIZATION_NAME, CREATED_BY, MODIFIED_BY) VALUES('Beta Organization', CURRENT_USER(), CURRENT_USER());

/*
SELECT *
FROM DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS
;
*/

INSERT INTO DOC_AI_DB.SECURITY_SCHEMA.USERS(ORGANIZATION_ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CREATED_BY, MODIFIED_BY)
SELECT O.ID, 'apatel', 'password', 'Ankur', 'Patel', 'ankurcp@gmail.com', CURRENT_USER(), CURRENT_USER()
FROM DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS O
WHERE O.ORGANIZATION_NAME = 'Alpha Corporation'
;

INSERT INTO DOC_AI_DB.SECURITY_SCHEMA.USERS(ORGANIZATION_ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CREATED_BY, MODIFIED_BY)
SELECT O.ID, 'spatel', 'password', 'Sinal', 'Patel', 'sinal_patel@hotmail.com', CURRENT_USER(), CURRENT_USER()
FROM DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS O
WHERE O.ORGANIZATION_NAME = 'Beta Organization'
;

/*
SELECT *
FROM DOC_AI_DB.SECURITY_SCHEMA.USERS
;
*/


CREATE OR REPLACE VIEW DOC_AI_DB.SECURITY_SCHEMA.USERS_ORGANIZATIONS AS
SELECT U.ID AS USER_ID, U.USER_NAME, U.PASSWORD, U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, O.ID AS ORGANIZATION_ID, O.ORGANIZATION_NAME 
FROM DOC_AI_DB.SECURITY_SCHEMA.USERS U
JOIN DOC_AI_DB.SECURITY_SCHEMA.ORGANIZATIONS O ON U.ORGANIZATION_ID=O.ID
;

/*
SELECT * 
FROM DOC_AI_DB.SECURITY_SCHEMA.USERS_ORGANIZATIONS
*/