USE DATABASE DOC_AI_DB;
USE SCHEMA SCHEDULED_TASKS;

CREATE OR REPLACE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_MANIFEST
(
    ID VARCHAR(16777216) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    JOB_NAME VARCHAR(16777216),
    START_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    END_DATE_TIME TIMESTAMP,
    FILES_PROCESSED INTEGER,
    FILES_SUCCESSFUL INTEGER,
    FILES_FAILED INTEGER,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(16777216),
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(16777216)
)
;


CREATE OR REPLACE TASK DOC_AI_DB.SCHEDULED_TASKS.PROCESS_BATCHES
    WAREHOUSE = 'DOC_AI_WH'
    SCHEDULE = 'USING CRON * 23 * * * UTC'
AS
BEGIN
    DROP TABLE IF EXISTS DOC_AI_DB.DOC_AI_SCHEMA.STAGED_FILES;

    CREATE TABLE DOC_AI_DB.DOC_AI_SCHEMA.STAGED_FILES AS
    SELECT 
        TRIM(SPLIT(RELATIVE_PATH, '/')[0], '"') AS BATCH_NAME,
        TRIM(SPLIT(RELATIVE_PATH, '/')[1], '"') AS FILE_NAME,
        RELATIVE_PATH AS FULL_FILE_NAME_PATH,
        SIZE AS FILE_SIZE,
        LAST_MODIFIED,
        FILE_URL AS SNOWFLAKE_FILE_URL,
        DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_CO_BRANDING!PREDICT(GET_PRESIGNED_URL('@DOC_AI_STAGE', RELATIVE_PATH), 1) AS PREDICT
    FROM DIRECTORY(@DOC_AI_STAGE)
    ;
END;
