USE DATABASE DOC_AI_DB;
USE SCHEMA SCHEDULED_TASKS;

CREATE OR REPLACE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_HEADER
(
    ID VARCHAR(16777216) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    JOB_NAME VARCHAR(16777216),
    START_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    END_DATE_TIME TIMESTAMP,
    FILES_PROCESSED INTEGER,
    FILES_SUCCESSFUL INTEGER,
    FILES_FAILED INTEGER,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(16777216),
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(16777216)
)
;

CREATE OR REPLACE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_DETAIL
(
    ID VARCHAR(16777216) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    SCHEDULED_TASK_HEADER_ID VARCHAR(16777216),
    BATCH_HEADER_ID VARCHAR(16777216),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(16777216),
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(16777216)
)
;
