SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL_STATUS;
SELECT * FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_HEADER;
SELECT * FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_DETAIL;


SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_DETAIL_ORGANIZATION_VIEW
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_ORGANIZATION_VIEW

LIST @DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_STAGE;
LIST @DOC_AI_DB.DOC_AI_SCHEMA.INSPECTION_STAGE;

SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL_STATUS' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL_STATUS UNION ALL
SELECT 'DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_HEADER' as TABLE_NAME, COUNT(*) as TOTAL  FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_HEADER UNION ALL
SELECT 'DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_DETAIL' as TABLE_NAME, COUNT(*) as TOTAL  FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_DETAIL UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_DETAIL_ORGANIZATION_VIEW' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_DETAIL_ORGANIZATION_VIEW UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_ORGANIZATION_VIEW' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_ORGANIZATION_VIEW


/*
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER;
--TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS;
--TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL;
--TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL_STATUS;
TRUNCATE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_HEADER;
TRUNCATE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_DETAIL;

REMOVE @DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_STAGE;
REMOVE @DOC_AI_DB.DOC_AI_SCHEMA.INSPECTION_STAGE;
*/