SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL_TYPE;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_HEADER;
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_DETAIL;
SELECT * FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_MANIFEST;

SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_DETAIL_ORGANIZATION_VIEW
SELECT * FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_ORGANIZATION_VIEW

LIST @DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_STAGE;

SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL_TYPE' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL_TYPE UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_HEADER' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_HEADER UNION ALL
SELECT 'DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_DETAIL' as TABLE_NAME, COUNT(*) as TOTAL FROM DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_DETAIL UNION ALL
SELECT 'DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_MANIFEST' as TABLE_NAME, COUNT(*) as TOTAL  FROM DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_MANIFEST;




/*
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_STATUS;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_HEADER_MODEL_TYPE;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.BATCH_DETAIL;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_HEADER;
TRUNCATE TABLE DOC_AI_DB.STREAMLIT_SCHEMA.ANALYSIS_DETAIL;
TRUNCATE TABLE DOC_AI_DB.SCHEDULED_TASKS.SCHEDULED_TASK_MANIFEST;

REMOVE @DOC_AI_DB.DOC_AI_SCHEMA.DOC_AI_STAGE;
*/